server:
  port: 9090

spring:
  application:
    name: COMMON-SERVICE
  datasource:
    url: jdbc:mariadb://localhost:3306/demodb?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comments: false
        format_sql: false
      open-in-view: true
      show-sql: true
      # Naming strategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
