server:
  port: 9090

spring:
  kafka:
    request.timeout.ms: 20000
    schema.registry.url: http://localhost:8081
    bootstrap.servers: http://localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      user-producer-event:
        topic: userEventTopic
        groupId: userEventTopic-microservice-producer
        clientId: userEvent-producer
  application:
    name: COMMON-SERVICE
  datasource:
    url: jdbc:mariadb://localhost:3306/demodb?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comments: false
        format_sql: false
      open-in-view: true
      show-sql: true
      # Naming strategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
